data:
  generator: sim_confounder
  params:
    nodes: 30
    k: [0, 1, 2, 3, 4]
    samples: 1000
    graph_type: ER
    edges_per_node: 8
    linear: True
    noise_scale: 1
    sem_type: gauss
    weight_range: [[.5, 2]]
    random_state: !range 5

analyzer: analyze_confounder

methods:
  ALIAS: !overwrite 
    FROM: !yml ALIAS_default.yml
    standardize_data: false
    dag_scorer_kwargs:
      regressor: LinearRegression
      variant: EV
    verbose: true