data:
  generator: sim_pe
  params:
    nodes:
      - 5
      - 10
      - 20
      - 30
    samples: 1000
    graph_type: ER
    edges_per_node:
      - 1
      - 2
    linear: True
    noise_scale: 1
    sem_type: gauss
    weight_range: 
      - [2, 5]
    random_state: !range 5

analyzer: analyze_linear

methods:
  ALIAS: !overwrite 
    FROM: !yml ALIAS_default.yml
    standardize_data: false
    dag_scorer_kwargs:
      regressor: LinearRegression
      variant: EV
    verbose: true