data:
  generator: sim_noisy
  params:
    nodes: 30
    samples: 1000
    graph_type: ER
    edges_per_node: 8
    linear: True
    noise_scale: 1
    sem_type: gauss
    p: [0., 0.01, .03, 0.05, .1]
    weight_range: [[.5, 2]]
    random_state: !range 5

analyzer: analyze_noisy

methods:
  ALIAS: !overwrite 
    FROM: !yml ALIAS_default.yml
    standardize_data: false
    dag_scorer_kwargs:
      regressor: LinearRegression
      variant: EV
    verbose: true